add-link-on-list-certificates
ita-social-projects/EPlast-Client pull request #1010
Opened 2022-07-14 13:20 UTC by Goven112

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-07-14 17:52 UTC, hryhoriivoloshyn approved these changes

2022-07-15 09:01 UTC, tvardero requested changes

2022-07-15 09:01 UTC, tvardero commented on src/pages/userPage/personalData/Course.tsx
> +                    onClick={() => showUploadWindow()
Теж, зайва функція, можно було зробити `() => setvisibleAchievementModal(true)`

2022-07-15 10:42 UTC, Goven112 commented on src/pages/userPage/personalData/Course.tsx
> +  const [userToken, setUserToken] = useState<any>([
ну це в іншому функціоналі так само зроблено тому я так само зробив

2022-07-15 10:44 UTC, Serhii-Buniak approved these changes

2022-07-17 16:03 UTC, Goven112 commented on src/pages/userPage/personalData/Course.tsx
deleted paragraphs

2022-07-17 16:03 UTC, Goven112 commented on src/pages/userPage/personalData/Course.tsx
> +                    onClick={() => showUploadWindow()
done

2022-07-17 16:03 UTC, Goven112 commented on src/pages/userPage/personalData/Course.tsx
> +  const showListCertificates = async () => {
done

2022-07-17 17:23 UTC, tvardero requested changes

2022-07-17 17:23 UTC, tvardero commented on src/pages/userPage/personalData/Course.tsx
> +  const [achievementDoc, setAchievementDoc] = useState<BlankDocument[]>([]);
Заміни на звичайну змінну

2022-07-18 08:38 UTC, tvardero approved these changes

2022-07-18 08:48 UTC, tvardero requested changes
Wait

2022-07-18 08:57 UTC, tvardero approved these changes

2022-07-18 09:45 UTC, merged