Fixed context menu Add/Change Degree
ita-social-projects/EPlast-Client pull request #1036
Opened 2022-08-01 07:59 UTC by hryhoriivoloshyn

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-01 08:01 UTC, vsynieok requested changes

2022-08-01 08:01 UTC, vsynieok commented on src/pages/UserTable/DropdownItem.tsx
> +      console.log("You can change user degree!");
remove console.log

2022-08-01 08:03 UTC, hryhoriivoloshyn commented on src/pages/UserTable/DropdownItem.tsx
> +      console.log("You can change user degree!");
Removed, thx

2022-08-01 08:05 UTC, vsynieok approved these changes

2022-08-01 08:09 UTC, tvardero approved these changes

2022-08-01 11:38 UTC, vsynieok approved these changes

2022-08-03 11:16 UTC, Serhii-Buniak approved these changes

2022-08-03 12:04 UTC, merged