2732 bug id
ita-social-projects/EPlast-Client pull request #1047
Opened 2022-08-18 17:39 UTC by gutovskii

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-21 08:41 UTC, tvardero commented on src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
> +      const yearsOld = Number(Math.floor(distance / 1000 / 60 / 60 / 24 / 365));
365.25 , не забувай про високосні роки

2022-08-21 08:45 UTC, tvardero requested changes
365.25

2022-08-21 12:05 UTC, vsynieok requested changes

2022-08-21 12:05 UTC, vsynieok commented on src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
> +      const yearsOld = Number(Math.floor(distance / 1000 / 60 / 60 / 24 / 365));
на проєкті використовується moment, тому краще не видумувати велосипед, а використати метод .diff(), який там вже є https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/07-difference/

2022-08-22 10:31 UTC, tvardero approved these changes

2022-08-22 10:43 UTC, hryhoriivoloshyn approved these changes

2022-08-23 11:10 UTC, vsynieok approved these changes

2022-08-23 16:05 UTC, merged