Fix #2762
ita-social-projects/EPlast-Client pull request #1052
Opened 2022-08-21 12:33 UTC by Mykola123-NMT

dev
## Mykola Nenchuk

## Code reviewers
Hryhorii Voloshyn
Vladyslaw Synieok
Serhii Buniak

2022-08-21 12:34 UTC, Mykola123-NMT commented
403 error when registered user clicked on the City Board users' profile/Профілі членів проводу станиці

2022-08-21 13:08 UTC, hryhoriivoloshyn requested changes

2022-08-21 13:08 UTC, hryhoriivoloshyn commented on src/pages/City/City/CityAdministration.tsx
> +                    canSeeProfiles ?
You can use "&&" operator instead of ternary operator here

2022-08-22 10:30 UTC, tvardero approved these changes

2022-08-22 10:42 UTC, hryhoriivoloshyn approved these changes

2022-08-23 05:58 UTC, vsynieok approved these changes

2022-08-24 04:51 UTC, tvardero requested changes
Broken commit history

2022-08-24 16:57 UTC, tvardero approved these changes

2022-09-21 14:57 UTC, tvardero requested changes
7 строк, 6 коммитов
скваш

2022-09-21 18:12 UTC, tvardero approved these changes

2022-09-25 19:22 UTC, merged