There was no opportunity to load and download files with dots in name
ita-social-projects/EPlast-Client pull request #1082
Opened 2022-09-02 12:55 UTC by gutovskii

I wrote '!' after pop() because file always has dot and extension after it

Closes https://github.com/ita-social-projects/EPlast/issues/2702

## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-09-02 13:40 UTC, hryhoriivoloshyn requested changes

2022-09-02 13:40 UTC, hryhoriivoloshyn commented on src/pages/userPage/Blanks/Blanks.tsx
> +                      extractUPU.blobName.split(".").pop()!
It would be better to add a constant instead of invoking split every time.

2022-09-02 13:40 UTC, hryhoriivoloshyn commented on src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx
> +                  item.fileName.split(".").pop()! !== "doc" &&
Use const instead of invoking method.

2022-09-05 14:44 UTC, Mykola123-NMT approved these changes

2022-09-05 16:33 UTC, hryhoriivoloshyn approved these changes

2022-09-06 08:55 UTC, vsynieok approved these changes

2022-09-06 09:07 UTC, merged