Added General Info and resposive to ActiveMembership
ita-social-projects/EPlast-Client pull request #151
Opened 2020-10-12 22:04 UTC by MarianLabensky

2020-10-13 10:49 UTC, voroniak requested changes

2020-10-13 10:49 UTC, voroniak commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        <DatePicker format = "YYYY-MM-DD"
```suggestion
        <DatePicker format = "DD-MM-YYYY" 
```
I think we are using this format

2020-10-13 10:49 UTC, voroniak commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        defaultValue = { dates.dateOath !== "" ? moment(dates.dateOath, 'YYYY-MM-DD') : undefined}
```suggestion
        defaultValue = { dates.dateOath !== "" ? moment(dates.dateOath, 'DD-MM-YYYY') : undefined}
```

2020-10-13 10:49 UTC, voroniak commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        defaultValue = { dates.dateEnd !== "" ? moment(dates.dateEnd, 'YYYY-MM-DD') : undefined}
```suggestion
        defaultValue = { dates.dateEnd !== "" ? moment(dates.dateEnd, 'DD-MM-YYYY') : undefined}
```

2020-10-13 10:49 UTC, voroniak commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        <DatePicker format = "YYYY-MM-DD"
```suggestion
        <DatePicker format = "DD-MM-YYYY" 
```

2020-10-13 11:35 UTC, MarianLabensky commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        <DatePicker format = "YYYY-MM-DD"
Done

2020-10-13 11:36 UTC, MarianLabensky commented on src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
> +        <DatePicker format = "YYYY-MM-DD"
Done

2020-10-13 13:08 UTC, voroniak approved these changes

2020-10-13 15:33 UTC, MykhailoKlapchuk approved these changes
Good job

2020-10-14 19:52 UTC, TonyWebber approved these changes

2020-10-14 20:16 UTC, merged