Added additional questions to region annual report
ita-social-projects/EPlast-Client pull request #252
Opened 2020-11-25 15:11 UTC by tetyanakutsko

2020-11-25 18:03 UTC, MarianLabensky approved these changes

2020-11-26 00:00 UTC, LanchevychMaxym requested changes

2020-11-27 14:52 UTC, bodnarira approved these changes

2020-11-27 18:55 UTC, MykhailoKlapchuk approved these changes

2020-12-01 17:59 UTC, tetyanakutsko commented on src/pages/AnnualReport/AnnualReportTable/ClubSelectModal/ClubSelectModal.tsx
> +          notificationLogic("success", "Річний звіт успішно створено");
done.thanks

2020-12-01 18:19 UTC, bodnarira approved these changes

2020-12-01 19:03 UTC, merged