Users table filter
ita-social-projects/EPlast-Client pull request #318
Opened 2021-02-12 10:22 UTC by sooooolo

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-02-20 02:44 UTC, voroniak requested changes

2021-02-20 02:44 UTC, voroniak commented on src/pages/UserTable/UserTable.module.css
> +/*.treeSelect{
Could you delete this?

2021-02-25 11:27 UTC, randomVovaKuhot approved these changes

2021-03-29 18:24 UTC, AlexKaschuk approved these changes

2021-03-29 18:27 UTC, vovikboyko approved these changes

2021-03-29 18:37 UTC, randomVovaKuhot approved these changes

2021-03-29 18:43 UTC, Lunaflumen approved these changes

2021-04-02 07:56 UTC, voroniak approved these changes
LGTM!

2021-04-02 07:57 UTC, merged