Edit profile bug fix
ita-social-projects/EPlast-Client pull request #322
Opened 2021-03-10 19:35 UTC by OlehHatsko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-11 14:24 UTC, randomVovaKuhot approved these changes

2021-03-13 11:54 UTC, Oleh-Bodnar approved these changes

2021-03-15 12:15 UTC, vovikboyko requested changes

2021-03-15 12:15 UTC, vovikboyko commented on src/pages/userPage/EditUserPage/EditUserPage.tsx
> +  const secondPatern = /^[a-zA-Zа-яА-ЯІіЄєЇїҐґ'"\(\).`()0-9]{0,50}((\s+|-)[a-zA-Zа-яА-ЯІіЄєЇїҐґ'"\(\).`()0-9]{0,50})*$/;
Please, make names more meaningful. pater and secondPatern is awful(

2021-03-15 12:16 UTC, tetyanakutsko approved these changes

2021-03-15 12:35 UTC, vovikboyko approved these changes

2021-03-15 12:58 UTC, merged