Create government body
ita-social-projects/EPlast-Client pull request #330
Opened 2021-03-21 11:21 UTC by OlehHatsko

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-23 16:24 UTC, vovikboyko requested changes

2021-03-23 16:24 UTC, vovikboyko commented on src/models/GoverningBody/GoverningBodyAdmin.tsx
> +}
missing empty row

2021-03-23 16:24 UTC, vovikboyko commented on src/models/GoverningBody/GoverningBodyForAdmin.tsx
> +}
missing empty row

2021-03-23 17:07 UTC, vovikboyko approved these changes

2021-03-29 12:35 UTC, Oleh-Bodnar approved these changes

2021-03-29 12:37 UTC, danylo-melnychuk approved these changes

2021-03-29 13:15 UTC, merged