AboutBase section
ita-social-projects/EPlast-Client pull request #481
Opened 2021-07-23 13:01 UTC by veronika-kolosova

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-23 18:00 UTC, OleksandrBilan requested changes

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +      // setData(res);
Do you need these comments?

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +        //onClick={() =>history.push(``)}
and this

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +        //onClick={()=>handleDelete(item.id)}
and here

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +            {
Why do you place here the '{' ??

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +            }
and here, i think you dont need these

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +    <Collapse
maybe some tabulation here?

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AboutBase.tsx
> +            //onAdd={handleAdd}
apply the correct tabulation, please

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/AskQuestionModal.tsx
> +         />
tabulation

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/Subsections.tsx
> +function callback(key: any) {
what is the point of this function?

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/Subsections.tsx
> +    {
bracket on previous line

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/Subsections.tsx
> +      //setData(prev => [...prev.slice(0, index + 1), newItem, ...prev.slice(index + 1)])
do something with the comments

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/Subsections.tsx
> +        //onClick={() =>history.push(``)}
comments

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/Subsections.tsx
> +    <div><TextEditor /></div>
tabulation

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/TextEditor.tsx
> +         form={form}>
tabulation

2021-07-23 18:00 UTC, OleksandrBilan commented on src/pages/AboutBase/TextEditor.tsx
> +            modules={modules}/> */}
remove comments

2021-07-26 19:27 UTC, christykobyletska approved these changes

2021-07-26 20:10 UTC, sharix4 approved these changes

2021-07-27 12:08 UTC, nicoolle approved these changes

2021-07-27 13:01 UTC, solomiyon approved these changes

2021-07-27 13:55 UTC, OleksandrBilan approved these changes

2021-07-27 14:09 UTC, merged