Adde active status sorting,
ita-social-projects/EPlast-Client pull request #495
Opened 2021-07-30 09:10 UTC by andrii52

archiving and unarchiving
Regions, Cities, Clubs

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-07-30 11:59 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.less
> +
delete space

2021-07-30 11:59 UTC, christykobyletska commented on src/pages/City/City/Form.module.css
> +
delete space

2021-07-30 12:01 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +
delete unnecessary spaces

2021-07-30 12:02 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +
delete unnecessary spaces

2021-07-30 12:02 UTC, christykobyletska commented on src/pages/City/Cities/ActionCities.tsx
> +
delete one space

2021-07-30 12:03 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +
delete one space

2021-07-30 12:03 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +
and here

2021-07-30 12:03 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +
and here

2021-07-30 12:04 UTC, christykobyletska commented on src/pages/Club/Club/Form.module.css
> +
delete space

2021-07-30 12:04 UTC, christykobyletska commented on src/pages/Regions/CheckActiveCitiesForm.less
> +
delete space

2021-08-01 11:08 UTC, andrii52 commented on src/pages/Club/Club/CheckActiveMembersForm.less
> +
Done

2021-08-01 11:37 UTC, christykobyletska requested changes

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/Cities/ActionCities.tsx
> +        }
closing brace should have the same tabulation as the opening one

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/Cities/SortedCities.tsx
> +    try{
put space after try

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/Cities/SortedCities.tsx
> +    }finally{
and here spaces

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/Cities/SortedCities.tsx
> +
need this space?

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +             />
add tabulation for title, classname, and closing tag, so it is on the same tab as opening tag

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +                  </Col>
and here please add tabulation (for p, col)

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +                className="site-page-header"
please add tabulation for props(title, classname)

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +                            key={follower.id}
add here tab

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +         htmlType="submit"
and for these props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +
do you need these space after button, form.item closing tags)?

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/CheckActiveMembersForm.tsx
> +
add here these 2 spaces?

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/City/City/City.tsx
> +                            </Col>
here shift+tab for /col

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +                    className="site-page-header"
please add tab for props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +                                    key={member.id}
tab

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +                         className="site-page-header"
tab for props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +                                </Col>
add tabulation here please

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +                />
add tabulation for props and closing tag

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/CheckActiveMembersForm.tsx
> +        >
tabulation for props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Club/Club.tsx
> +                            </Col>
shift+tab for /col

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Clubs/ActionClubs.tsx
> +            <SortedClubs switcher={SwitchValue} />
add tab

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Clubs/SortedClubs.tsx
> +    try{
space after try

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Clubs/SortedClubs.tsx
> +    }finally{
here after and before finaly

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Club/Clubs/SortedClubs.tsx
> +              onClick={() => history.push(`${url}/${city.id}`)}
add tab for props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Regions/CheckActiveCitiesForm.tsx
> +            htmlType="submit"
add tabulation for props

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Regions/Region.tsx
> +    }finally{
spaces

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Regions/Region.tsx
> +                  Заархівовано
please add tab

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Regions/Region.tsx
> +                                  </Col>
shift+tab for /col

2021-08-01 11:37 UTC, christykobyletska commented on src/pages/Regions/SortedRegions.tsx
> +              key={region.id}
please tabulate inside <card> </card>

2021-08-01 13:29 UTC, christykobyletska approved these changes

2021-08-01 14:54 UTC, OleksandrBilan approved these changes

2021-08-01 16:12 UTC, voroniak requested changes

2021-08-01 16:12 UTC, voroniak commented on src/api/clubsApi.tsx
> +  return api
Add await

2021-08-01 16:12 UTC, voroniak commented on src/api/clubsApi.tsx
> +  return api.put(`Club/ArchiveClub/${id}`).catch((error) => {
The same

2021-08-01 16:46 UTC, andrii52 commented on src/api/clubsApi.tsx
> +  return api
Done

2021-08-02 18:09 UTC, nicoolle approved these changes

2021-08-03 07:43 UTC, voroniak approved these changes

2021-08-03 14:39 UTC, merged