legislation security
ita-social-projects/EPlast-Client pull request #934
Opened 2022-05-29 17:59 UTC by Serhii-Buniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-05-29 18:36 UTC, tvardero requested changes

2022-05-29 18:36 UTC, tvardero commented on src/pages/Documents/DropDownDocuments.tsx
> +      setCanEdit(roles.includes(Roles.Admin) || roles.includes(Roles.GoverningBodyAdmin));
Make it constant, not a state (in the beggining of file)
`const isAdmin = roles.includes....`

No need to use states (and agro react to rerender page).

2022-05-30 11:46 UTC, Omeliukh-Nazar approved these changes

2022-05-31 15:36 UTC, tvardero approved these changes

2022-06-01 23:19 UTC, merged