Bug/#add-levels-city
ita-social-projects/EPlast-Client pull request #960
Opened 2022-06-11 23:12 UTC by Goven112

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-06-13 07:19 UTC, Omeliukh-Nazar approved these changes

2022-06-13 08:17 UTC, tvardero requested changes

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CityDetailDrawer/CityDetailDrawer.tsx
> +              name="adress"
ad**d**ress

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CityDetailDrawer/CityDetailDrawer.tsx
> +                props.city.level > 0 ? props.city.level : "---"
Move `"---"` to `placeholder` attribute. Don't use it as initial value

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CityDetailDrawer/CityDetailDrawer.tsx
> +                props.city.level > 0 ? props.city.level : "---"
Because if accidentally form will be sent, `"---"` will be sent as well.

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CityDetailDrawer/CityDetailDrawer.tsx
> -                  props.city.postIndex?.length > 0
Don't use both `initialValue` attribute in `Form.Item` and `value` attribute in `Input`. 
Use only one, preferably `initialValue` attribute in `Form.Item`.

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CityDetailDrawer/CityDetailDrawer.tsx
>                      : "---"
Same here with `"---"`

2022-06-13 08:17 UTC, tvardero commented on src/pages/City/CreateCity/CreateCity.tsx
> +        adress: values.adress,
ad**d**ress

2022-06-15 11:27 UTC, DimaDiD approved these changes

2022-06-16 10:37 UTC, tvardero approved these changes

2022-06-20 08:46 UTC, merged