CreateCity form bugfixes
ita-social-projects/EPlast-Client pull request #990
Opened 2022-07-01 11:51 UTC by vsynieok

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-07-01 18:52 UTC, Serhii-Buniak approved these changes

2022-07-02 13:35 UTC, tvardero commented on src/models/GllobalValidations/DescriptionValidation.tsx
> +      pattern: /^\S*((?=([А-ЯҐЄІЇа-яґєії\d]+[\.\-\,']?))\2\s?)+$/,
Додай 0-9, тому що адреса може бути "вул. 8ме березня"

2022-07-04 08:48 UTC, vsynieok commented on src/models/GllobalValidations/DescriptionValidation.tsx
> +      pattern: /^\S*((?=([А-ЯҐЄІЇа-яґєії\d]+[\.\-\,']?))\2\s?)+$/,
![image](https://user-images.githubusercontent.com/55637550/177118456-58eef92a-aec9-4704-836f-e0fc28406800.png)

The current pattern matches your example without any problems.

2022-07-04 09:41 UTC, tvardero requested changes

2022-07-05 08:28 UTC, tvardero approved these changes

2022-07-05 11:48 UTC, hryhoriivoloshyn approved these changes

2022-07-05 11:48 UTC, merged